theme: jekyll-theme-minimal
title: Hello!
description: Basic info about me
logo: assets/profile.jpg
email: bbatalo@hotmail.com
# linkedin: bojan-batalo
# researchgate: Bojan-Batalo
kramdown:  
  parse_block_html: true